USE [master]
GO

/****** Object:  Database [CoreUserData]    Script Date: 3/27/2022 3:55:12 PM ******/
DROP DATABASE [CoreUserData]
GO

/****** Object:  Database [CoreUserData]    Script Date: 3/27/2022 3:55:12 PM ******/
CREATE DATABASE [CoreUserData]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CoreUserData', FILENAME = N'D:\!!!All_Software_Install\SqlServerManagement\MSSQL15.LOCALMSSQLSERVER\MSSQL\DATA\CoreUserData.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CoreUserData_log', FILENAME = N'D:\!!!All_Software_Install\SqlServerManagement\MSSQL15.LOCALMSSQLSERVER\MSSQL\DATA\CoreUserData_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CoreUserData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CoreUserData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CoreUserData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CoreUserData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CoreUserData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CoreUserData] SET ARITHABORT OFF 
GO

ALTER DATABASE [CoreUserData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CoreUserData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CoreUserData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CoreUserData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CoreUserData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CoreUserData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CoreUserData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CoreUserData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CoreUserData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CoreUserData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CoreUserData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CoreUserData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CoreUserData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CoreUserData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CoreUserData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CoreUserData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CoreUserData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CoreUserData] SET RECOVERY FULL 
GO

ALTER DATABASE [CoreUserData] SET  MULTI_USER 
GO

ALTER DATABASE [CoreUserData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CoreUserData] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CoreUserData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CoreUserData] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CoreUserData] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CoreUserData] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CoreUserData] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CoreUserData] SET  READ_WRITE 
GO

